import Image from "next/image";
import Head from "next/head";
import { Inter } from "@next/font/google";
import type { GetStaticProps } from "next";

import { ContentLayout } from "@/components/contentLayout";
import { Profile } from "@/components/profile";
import { BlogList } from "@/components/blogList";
import { WordsList } from "@/components/wordsList";
import type { AllPostsData } from "../types/blog";
import { getStoredPostsData } from "../lib/post";
import { getStoredWordsData } from "../lib/word";
import styles from "./page.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  allPostsData,
  allWordsData,
}: {
  allPostsData: AllPostsData;
  allWordsData: AllPostsData;
}) {
  return (
    <>
      <Head>
        <title>programmerzbb</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/my-logo.svg" />
      </Head>
      <ContentLayout>
        <main className={styles.wrap}>
          <Profile />
          <BlogList allPostsData={allPostsData} />
          <WordsList allPostsData={allWordsData} />
        </main>
      </ContentLayout>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const allPostsData = await getStoredPostsData();
  const allWordsData = await getStoredWordsData();
  return {
    props: {
      allPostsData,
      allWordsData,
    },
  };
};
